// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Wappa.Infraestrutura.Contexto;

namespace Wappa.Infraestrutura.Migrations
{
    [DbContext(typeof(WappaContexto))]
    [Migration("20180527203154_WappaMigration")]
    partial class WappaMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wappa.Dominio.Entidade.Carro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Cor")
                        .HasColumnName("COR")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<int>("IdMotorista")
                        .HasColumnName("ID_MOTORISTA");

                    b.Property<int?>("Lugar")
                        .HasColumnName("LUGAR")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int?>("Mala")
                        .HasColumnName("MALA")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Marca")
                        .HasColumnName("MARCA")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("Modelo")
                        .HasColumnName("MODELO")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Placa")
                        .HasColumnName("PLACA")
                        .HasMaxLength(8)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdMotorista")
                        .HasName("FK_CARRO_MOTORISTA");

                    b.ToTable("TB_CARRO");
                });

            modelBuilder.Entity("Wappa.Dominio.Entidade.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Cep")
                        .HasColumnName("CEP")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Complemento")
                        .HasColumnName("COMPLEMENTO")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<int>("IdMotorista")
                        .HasColumnName("ID_MOTORISTA");

                    b.Property<double?>("Latitude")
                        .HasColumnName("LATITUDE")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<string>("Logradouro")
                        .HasColumnName("LOGRADOURO")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<double?>("Longitude")
                        .HasColumnName("LONGITUDE")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int>("Numero")
                        .HasColumnName("NUMERO")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdMotorista")
                        .HasName("FK_ENDERECO_MOTORISTA");

                    b.ToTable("TB_ENDERECO");
                });

            modelBuilder.Entity("Wappa.Dominio.Entidade.Motorista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID");

                    b.Property<string>("Nome")
                        .HasColumnName("NOME")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.Property<string>("Sobrenome")
                        .HasColumnName("SOBRENOME")
                        .HasMaxLength(55)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("TB_MOTORISTA");
                });

            modelBuilder.Entity("Wappa.Dominio.Entidade.Carro", b =>
                {
                    b.HasOne("Wappa.Dominio.Entidade.Motorista", "Motorista")
                        .WithMany("ListaCarro")
                        .HasForeignKey("IdMotorista");
                });

            modelBuilder.Entity("Wappa.Dominio.Entidade.Endereco", b =>
                {
                    b.HasOne("Wappa.Dominio.Entidade.Motorista", "Motorista")
                        .WithMany("ListaEndereco")
                        .HasForeignKey("IdMotorista");
                });
#pragma warning restore 612, 618
        }
    }
}
