// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Wappa.DataAccess;

namespace Wappa.DataAccess.Migrations
{
    [DbContext(typeof(WappaDbContext))]
    [Migration("20180309012303_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wappa.Models.Taxista", b =>
                {
                    b.Property<int?>("IdTaxista")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Latitude")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("Longitude")
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)")
                        .HasMaxLength(8);

                    b.Property<string>("PrimeiroNome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UltimoNome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.HasKey("IdTaxista");

                    b.ToTable("Taxistas");
                });
#pragma warning restore 612, 618
        }
    }
}
