CREATE TABLE ESTADO (
	ESTADOID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DESCRICAO VARCHAR(255) NOT NULL,
    SIGLA VARCHAR(2) NOT NULL
) ENGINE=INNODB;

CREATE TABLE CIDADE (
	CIDADEID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ESTADOID INTEGER NOT NULL,
    NOME VARCHAR(255),
    FOREIGN KEY (ESTADOID) REFERENCES ESTADO(ESTADOID)
) ENGINE=INNODB;

CREATE TABLE CARRO (
	CARROID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    MARCA VARCHAR(255) NOT NULL,
    PLACA VARCHAR(255) NOT NULL
) ENGINE=INNODB;



CREATE TABLE MOTORISTA (
	MOTORISTAID INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOME VARCHAR(255) NOT NULL,
    SOBRENOME VARCHAR(255) NOT NULL,
    CARROID INTEGER NOT NULL,
    LOGRADOURO VARCHAR(255) NOT NULL,
    NUMERO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    CIDADEID INTEGER NOT NULL,
    LATITUDE DECIMAL(10,8) NOT NULL,
    LONGITUDE DECIMAL(11,8) NOT NULL,
    FOREIGN KEY (CARROID) REFERENCES CARRO(CARROID),
    FOREIGN KEY (CIDADEID) REFERENCES CIDADE(CIDADEID)
) ENGINE=INNODB;

CREATE INDEX IX_MOTORISTA_PORNOME ON MOTORISTA(NOME);
CREATE INDEX IX_MOTORISTA_PORSOBRENOME ON MOTORISTA(SOBRENOME);

INSERT INTO ESTADO (DESCRICAO, SIGLA) VALUES ('São Paulo', 'SP');
INSERT INTO ESTADO (DESCRICAO, SIGLA) VALUES ('Rio de Janeiro', 'RJ');

INSERT INTO CIDADE (ESTADOID, NOME) VALUES (1, 'Barueri');
INSERT INTO CIDADE (ESTADOID, NOME) VALUES (2, 'Petropolis');

INSERT INTO CARRO (MARCA, PLACA) VALUES ('Volkswagen', 'ABC-1234');
INSERT INTO CARRO (MARCA, PLACA) VALUES ('Chevrolet', 'DDS-1555');


INSERT INTO MOTORISTA 
(NOME, SOBRENOME, CARROID, LOGRADOURO, NUMERO, BAIRRO, CEP, CIDADEID, LATITUDE, LONGITUDE)
VALUES
('Eduardo', 'Roberto', 1, 'Rua Teste', '123', 'Vila Teste', '01001-001', 1, 20.00000, 21.000000);

INSERT INTO MOTORISTA 
(NOME, SOBRENOME, CARROID, LOGRADOURO, NUMERO, BAIRRO, CEP, CIDADEID, LATITUDE, LONGITUDE)
VALUES
('Fulano', 'Ciclano', 2, 'Rua Teste', '123', 'Vila Teste', '01001-001', 2, 08.00000, -16.000000);


DELIMITER $$
CREATE PROCEDURE PROC_SELECT_MOTORISTA(IN ORDER_PARAMETER INT)
BEGIN
	SELECT * FROM MOTORISTA MOT
	JOIN CARRO CAR ON MOT.CARROID = CAR.CARROID
	JOIN CIDADE CID ON MOT.CIDADEID = CID.CIDADEID
	JOIN ESTADO EST ON CID.ESTADOID = EST.ESTADOID
	ORDER BY
		CASE WHEN ORDER_PARAMETER=1 THEN MOT.NOME END ASC,
		CASE WHEN ORDER_PARAMETER=2 THEN MOT.SOBRENOME END ASC;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_SELECT_ID_MOTORISTA(IN ID INT)
BEGIN
	SELECT * FROM MOTORISTA MOT
	JOIN CARRO CAR ON MOT.CARROID = CAR.CARROID
	JOIN CIDADE CID ON MOT.CIDADEID = CID.CIDADEID
	JOIN ESTADO EST ON CID.ESTADOID = EST.ESTADOID
    WHERE MOTORISTAID = ID;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_INSERT_MOTORISTA(
	IN P_NOME VARCHAR(255),
    IN P_SOBRENOME VARCHAR(255),
    IN P_CARROID INT,
    IN P_LOGRADOURO VARCHAR(255),
    IN P_NUMERO VARCHAR(255),
    IN P_BAIRRO VARCHAR(255),
    IN P_CEP VARCHAR(9),
    IN P_CIDADEID INT,
    IN P_LATITUDE VARCHAR(255),
    IN P_LONGITUDE VARCHAR(255)    
)
BEGIN
	INSERT INTO MOTORISTA 
	(NOME, SOBRENOME, CARROID, LOGRADOURO, NUMERO, BAIRRO, CEP, CIDADEID, LATITUDE, LONGITUDE)
	VALUES
	(P_NOME, P_SOBRENOME, P_CARROID, P_LOGRADOURO, P_NUMERO, P_BAIRRO, P_CEP, P_CIDADEID, P_LATITUDE, P_LONGITUDE);
    SELECT LAST_INSERT_ID();
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_UPDATE_MOTORISTA(
	IN P_ID INT,
	IN P_NOME VARCHAR(255),
    IN P_SOBRENOME VARCHAR(255),
    IN P_CARROID INT,
    IN P_LOGRADOURO VARCHAR(255),
    IN P_NUMERO VARCHAR(255),
    IN P_BAIRRO VARCHAR(255),
    IN P_CEP VARCHAR(9),
    IN P_CIDADEID INT,
    IN P_LATITUDE VARCHAR(255),
    IN P_LONGITUDE VARCHAR(255)    
)
BEGIN
	UPDATE MOTORISTA SET
		NOME = P_NOME,
        SOBRENOME = P_SOBRENOME,
        CARROID = P_CARROID,
        LOGRADOURO = P_LOGRADOURO,
        NUMERO = P_NUMERO,
        BAIRRO = P_BAIRRO,
        CEP = P_CEP,
        CIDADEID = P_CIDADEID,
        LATITUDE = P_LATITUDE,
        LONGITUDE = P_LONGITUDE 
	WHERE MOTORISTAID = P_ID;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_DELETE_MOTORISTA(
	IN ID INT
)
BEGIN
	DELETE FROM MOTORISTA WHERE MOTORISTAID = ID;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_SELECT_CIDADE()
BEGIN
	SELECT * FROM CIDADE CID
	JOIN ESTADO EST ON CID.ESTADOID = EST.ESTADOID;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_SELECT_ID_CIDADE(IN ID INT)
BEGIN
	SELECT * FROM CIDADE CID
	JOIN ESTADO EST ON CID.ESTADOID = EST.ESTADOID
    WHERE CID.CIDADEID = ID;
END $$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE PROC_SELECT_CARRO()
BEGIN
	SELECT * FROM CARRO;
END $$
DELIMITER ;


DELIMITER $$
CREATE PROCEDURE PROC_SELECT_ID_CARRO(IN ID INT)
BEGIN
	SELECT * FROM CARRO
	WHERE CARROID = ID;
END $$
DELIMITER ;
