USE wkenjico_test_wappa
GO

IF EXISTS(SELECT 1 FROM SYSOBJECTS WITH(NOLOCK) WHERE XTYPE = 'U' AND NAME = 'TBL_ADDRESS')
	DROP TABLE TBL_ADDRESS
GO

CREATE TABLE TBL_ADDRESS(
	ID					INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	, [NAME]			VARCHAR(255)
	, NUMBER			INT
	, NEIGHBORHOOD		VARCHAR(255)
	, POSTAL_CODE		VARCHAR(9)
	, [STATE]			VARCHAR(2)
	, LONGITUDE			DECIMAL(20,15)
	, LATITUDE			DECIMAL(20,15)
	, DRIVER_ID			INT
	, CITY				VARCHAR(200)
);

IF EXISTS(SELECT 1 FROM SYSOBJECTS WITH(NOLOCK) WHERE XTYPE = 'U' AND NAME = 'TBL_CAR')
	DROP TABLE TBL_CAR
GO

CREATE TABLE TBL_CAR (
	ID					INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	, BRAND				VARCHAR(200)
	, MODEL				VARCHAR(300)
	, PLATE				VARCHAR(8)
	, DRIVER_ID			INT
);

IF EXISTS(SELECT 1 FROM SYSOBJECTS WITH(NOLOCK) WHERE XTYPE = 'U' AND NAME = 'TBL_DRIVER')
	DROP TABLE TBL_DRIVER
GO

CREATE TABLE TBL_DRIVER (
	ID				INT IDENTITY(1,1) NOT NULL PRIMARY KEY
	, FIRST_NAME	VARCHAR(500)
	, LAST_NAME		VARCHAR(500)
);